name: proselint

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install prereqs
        run: sudo apt-get install python3-proselint

      # config file help: https://github.com/amperser/proselint/
      - name: create proselint config
        run: |
          cat <<JSON > $HOME/.proselintrc
          {
            "checks": {
              "typography.diacritical_marks": false,
              "typography.symbols": false,
              "annotations.misc": false,
              "security.password": false
            }
          }
          JSON

      - name: check prose
        run: a=`git ls-files '*.md'` && proselint $a
